### ISSUE TITLE
Cannot get it work with belongsToMany associations.

### ISSUE THREAD

**Issue by jesusbv** [cesardeazevedo/sails-hook-sequelize-blueprints#3]
I set the through relation with

``` js
Country.belongsToMany(Article, {
        as: 'articles',
        through: {
          model: 'CountryArticle'
        },
        foreignKey: {
          name: 'countryId',
          as: 'articles'
        }
    });

  Article.belongsToMany(Country, {
      as: 'countries',
      through: {
        model: 'CountryArticle'
      },
      foreignKey: {
        name: 'articleId',
        as: 'countries'
      }
    });
```

It creates the through model and if I do
POST /country/uuid/articles?attribute=Value...

populate the article table but not the through model

**Comment by cesardeazevedo** [comment]
I've not tested with `belongsToMany`, i'll take a look.

**Comment by jesusbv** [comment]
Thank you. 
https://media3.giphy.com/media/rwIMKq5weEYlq/200.gif

**Comment by cesardeazevedo** [comment]
This is actually a fork from the original sails / waterline blueprints, and even waterline doesn't support through associations http://sailsjs.org/documentation/concepts/models-and-orm/associations/through-associations, so it will require a different implementation to support it.

for now, i suggest you to create an additional model as an intermediary instead of using through association.

**Comment by jesusbv** [comment]
Thanks. How would it be the relations?
ModelA hasMany throughModel
ModelB hasMany throughModel

throughModel belongsTo ModelA
throughModel belongsTo ModelB?

with FK tableIdA and tableIdB.
UPDATE
just read the link. Thank you.

**Comment by cesardeazevedo** [comment]
#10
